export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

export const STORE_ALL_TRANSACTIONS = 'STORE_ALL_TRANSACTIONS'
export const THREE_MONTHS_TRANSACTIONS = 'THREE_MONTHS_TRANSACTIONS'

export const STORE_ACCOUNTS = 'STORE_ACCOUNTS'

export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'