export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

export const STORE_ALL_TRANSACTIONS = 'STORE_ALL_TRANSACTIONS'
export const STORE_LAST_TWO_MONTHS = 'STORE_LAST_TWO_MONTHS'
export const STORE_DEBITS = 'STORE_DEBITS'
export const STORE_CREDITS = 'STORE_CREDITS'


export const STORE_ACCOUNTS = 'STORE_ACCOUNTS'
export const STORE_POTS = 'STORE_POTS'

export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
export const SET_START_DAY_WEEK = 'SET_START_DAY_WEEK'
export const SET_START_DATE_MONTH = 'SET_START_DATE_MONTH'

export const DEBIT_CATEGORIES = 'DEBIT_CATEGORIES'
export const CREDIT_CATEGORIES = 'CREDIT_CATEGORIES'
