export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const STORE_ALL_TRANSACTIONS = 'STORE_ALL_TRANSACTIONS'
export const STORE_LAST_TWO_MONTHS = 'STORE_LAST_TWO_MONTHS'
export const STORE_DEBITS = 'STORE_DEBITS'
export const STORE_CREDITS = 'STORE_CREDITS'

export const STORE_ACCOUNTS = 'STORE_ACCOUNTS'
export const STORE_POTS = 'STORE_POTS'

export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
export const SET_START_DAY_WEEK = 'SET_START_DAY_WEEK'
export const SET_START_DATE_MONTH = 'SET_START_DATE_MONTH'

export const DEBIT_CATEGORIES = 'DEBIT_CATEGORIES'
export const CREDIT_CATEGORIES = 'CREDIT_CATEGORIES'

export const GET_BUDGET_CATEGORIES = 'GET_BUDGET_CATEGORIES'
export const SET_BUDGET_CATEGORIES = 'SET_BUDGET_CATEGORIES'
export const PUT_BUDGET_CATEGORIES = 'PUT_BUDGET_CATEGORIES'
export const STORE_CURRENT_SPENDING = 'STORE_CURRENT_SPENDING'

export const SET_VIEW = 'SET_VIEW'

export const SET_BC_IS_FETCHING = 'SET_BC_IS_FETCHING'
export const SET_BC_FETCHING_SUCCESS = 'SET_BC_FETCHING_SUCCESS'
export const SET_BC_FETCH_ERROR = 'SET_BC_FETCH_ERROR'
